// api/verify-license.js
// Verifies license keys generated by the SamCart webhook system.

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, message: 'Method not allowed' });
  }

  let body = req.body;
  if (typeof body === 'string') {
    try { body = JSON.parse(body); } catch (e) { body = {}; }
  }

  const { licenseKey, alreadyActivated } = body || {};

  if (!licenseKey || typeof licenseKey !== 'string') {
    return res.status(400).json({ success: false, message: 'Please enter a license key.' });
  }

  // Initialize key store if needed
  if (!global.licenseKeys) {
    global.licenseKeys = {};
  }

  const keyData = global.licenseKeys[licenseKey.trim().toUpperCase()];

  if (!keyData) {
    return res.status(200).json({
      success: false,
      message: "That license key isn't valid. Double-check your email from Lindsay and try again.",
    });
  }

  const MAX_DEVICES = 3;

  // Check device limit for new activations
  if (!alreadyActivated && keyData.uses >= MAX_DEVICES) {
    return res.status(200).json({
      success: false,
      message: `This license has already been activated on ${MAX_DEVICES} devices. Need help? Email restandrootholistichealing@gmail.com`,
    });
  }

  // Increment use count for new activations
  if (!alreadyActivated) {
    global.licenseKeys[licenseKey.trim().toUpperCase()].uses += 1;
  }

  return res.status(200).json({
    success: true,
    buyerEmail: keyData.email,
    buyerName: keyData.name,
    usesCount: keyData.uses,
    maxDevices: MAX_DEVICES,
  });
}
